### ISSUE TITLE
Add LDR support

### ISSUE THREAD

**Issue by Floppy** [giacecco/bricklink-helper#6]
So LDraw models can be imported. See https://github.com/Floppy/MOCs/blob/gh-pages/TIE%20Avenger/TIE%20Avenger.ldr (and others in the same repo) for an example.

Might need some translation of LDraw part IDs to bricklink IDs. Not sure. Rebrickable may help here.

**Comment by giacecco** [comment]
Done, I'll leave the testing to Floppy.
